version: '3.8'
services:
  nextjs:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV
    volumes:
      - ./public:/app/public
    env_file:
      - .env.production
