version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      # Passe tes variables ici ou via un fichier .env
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped
