version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      HOSTNAME: 0.0.0.0
      PORT: ${PORT:-3000}
      # (facultatif) variables serveur non publiques :
      API_BASE_URL: ${API_BASE_URL:-}

    volumes:
      - ./public:/app/public
