version: "3.9"

networks:
  web:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
      AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
      AIRTABLE_TABLE_ID: ${AIRTABLE_TABLE_ID}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    networks:
      - web
    restart: unless-stopped
